[options]
directory = /var/lib/behind
port = 5300

[logging]
file = /var/log/behind/behind.log
;file = /tmp/behind.log

[forward-zone]
forward-addr = 2001:4860:4860::8888
forward-addr = 2001:4860:4860::8844
forward-addr = 2606:4700:4700::1111
forward-addr = 2606:4700:4700::1001
;forward-addr = 2a10:50c0::ad1:ff
;forward-addr = 2a10:50c0::ad2:ff
;forward-addr = 8.8.8.8
;forward-addr = 1.1.1.1

[security]
case-randomize = yes

[filter]
include nxdomain.conf
;nodata-aaaa = example.com

[hosts]
printer1.lan = 192.168.0.230
