[forward-zone]
;forward-addr = 8.8.8.8
;forward-addr = 2001:4860:4860::8888
forward-addr = 2a10:50c0::ad1:ff
;forward-addr = 2a10:50c0::ad2:ff

[security]
case-randomize = yes

[nxdomain]
addr=doubleclick.net

[hosts]
printer1.lan = 192.168.123.123
